title:             A Guide To Interdisciplinary Education
email:             your-email@example.com
description:       A Guide To Interdisciplinary Education
author:            IEGuide @UCSB
baseurl:           "/"
url:               "http://ieguide.github.io"

# Social Profiles
#twitter_username:  ieguide
#github_username:   IEGuide
#facebook_username: IEGuide

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
