title:             Ehsan Sayyad
email:             ehsanATmatDOTucsbDOTedu
description:       Ehsan Sayyad is a Virtual Reality researcher, Interested in computer graphics and HCI.
author:            Ehsan Sayyad
baseurl:           "/"
url:               "http://www.ehsansayyad.com"

# Social Profiles
#twitter_username:  
#github_username:   
#facebook_username: 

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
